name: CMakeTest CI
on:
  pull_request:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake: [3.16.3]
    env:
      cmake_version: ${{ matrix.cmake }}
      os: Linux-x86_64
    steps:
      - uses: actions/checkout@v1
      - name: get cmake
        run: |
          url_prefix=https://github.com/Kitware/CMake/releases/download
          url_end=v${cmake_version}/cmake-${cmake_version}-${os}.sh
          wget "${url_prefix}/${url_end}"
          yes | /bin/sh "cmake-${cmake_version}-${os}.sh"
      - name: configure
        run: |
          cmake-${cmake_version}-${os}/bin/cmake -H. -Bbuild -DBUILD_TESTING=ON
      - name: unit_test
        run: |
          cd build
          cmake-${cmake_version}-${os}/bin/ctest  -j 2 --output-on-failure

#  docs_test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - uses: ammaraskar/sphinx-action@master
#      with:
#        docs-folder: "docs/"
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
